version: '3.7'

services:
  bash: &base
    build: .
    image: aawg-buildroot
    volumes:
      - .:/app
      - dl:/app/buildroot/dl
      - output:/app/buildroot/output
      - ccache:/root/.ccache
    working_dir: /app/buildroot
    command: bash
    environment:
      - CCACHE_DIR=/root/.ccache
      - BR2_CCACHE=y
      - BR2_CCACHE_DIR=/root/.ccache
      - BR2_JLEVEL=8
  
  # Base system image build without Python package
  build_base_image: &build_base
    <<: *base
    command: bash -x -c "make BR2_EXTERNAL=../aa_wireless_dongle/ O=output/$${BOARD_NAME} $${BOARD_NAME}_defconfig && 
      cd output/$${BOARD_NAME} && 
      echo 'BR2_CCACHE=y' >> .config && 
      echo 'BR2_CCACHE_DIR=\"/root/.ccache\"' >> .config && 
      echo 'BR2_JLEVEL=8' >> .config && 
      echo '# BR2_PACKAGE_AAWG is not set' >> .config && 
      make && 
      mkdir -p /app/images/ && 
      cp images/sdcard.img /app/images/base-$${BOARD_NAME}.img"

  # Python package build only
  build_python: &build_python
    <<: *base
    working_dir: /app/aa_wireless_dongle/package/aawg/src
    command: bash -x -c "
      python3 -m pip install --user build && 
      protoc --python_out=. --proto_path=proto proto/*.proto && 
      python3 -m build --wheel --outdir /app/images/python_pkg/"

  # Full image build including Python package
  build_full_image: &build_full
    <<: *base
    command: bash -x -c "make BR2_EXTERNAL=../aa_wireless_dongle/ O=output/$${BOARD_NAME} $${BOARD_NAME}_defconfig && 
      cd output/$${BOARD_NAME} && 
      echo 'BR2_CCACHE=y' >> .config && 
      echo 'BR2_CCACHE_DIR=\"/root/.ccache\"' >> .config && 
      echo 'BR2_JLEVEL=8' >> .config && 
      make && 
      mkdir -p /app/images/ && 
      cp images/sdcard.img /app/images/full-$${BOARD_NAME}.img"

  # Board-specific configurations
  rpi02w_base:
    <<: *build_base
    environment:
      - BOARD_NAME=raspberrypizero2w
      - CCACHE_DIR=/root/.ccache
      - BR2_CCACHE=y
      - BR2_CCACHE_DIR=/root/.ccache
      - BR2_JLEVEL=8

  rpi02w_python:
    <<: *build_python

  rpi02w_full:
    <<: *build_full
    environment:
      - BOARD_NAME=raspberrypizero2w
      - CCACHE_DIR=/root/.ccache
      - BR2_CCACHE=y
      - BR2_CCACHE_DIR=/root/.ccache
      - BR2_JLEVEL=8

volumes:
  dl:
  output:
  ccache:
