# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WifiInfoResponse.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'WifiInfoResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16WifiInfoResponse.proto\"\x8f\x01\n\x10WifiInfoResponse\x12\x0c\n\x04ssid\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\r\n\x05\x62ssid\x18\x03 \x02(\t\x12$\n\rsecurity_mode\x18\x04 \x02(\x0e\x32\r.SecurityMode\x12+\n\x11\x61\x63\x63\x65ss_point_type\x18\x05 \x02(\x0e\x32\x10.AccessPointType**\n\x0f\x41\x63\x63\x65ssPointType\x12\n\n\x06STATIC\x10\x00\x12\x0b\n\x07\x44YNAMIC\x10\x01*\xca\x01\n\x0cSecurityMode\x12\x19\n\x15UNKNOWN_SECURITY_MODE\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\n\n\x06WEP_64\x10\x02\x12\x0b\n\x07WEP_128\x10\x03\x12\x10\n\x0cWPA_PERSONAL\x10\x04\x12\x11\n\rWPA2_PERSONAL\x10\x08\x12\x15\n\x11WPA_WPA2_PERSONAL\x10\x0c\x12\x12\n\x0eWPA_ENTERPRISE\x10\x14\x12\x13\n\x0fWPA2_ENTERPRISE\x10\x18\x12\x17\n\x13WPA_WPA2_ENTERPRISE\x10\x1c\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WifiInfoResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ACCESSPOINTTYPE']._serialized_start=172
  _globals['_ACCESSPOINTTYPE']._serialized_end=214
  _globals['_SECURITYMODE']._serialized_start=217
  _globals['_SECURITYMODE']._serialized_end=419
  _globals['_WIFIINFORESPONSE']._serialized_start=27
  _globals['_WIFIINFORESPONSE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
