#!/bin/sh

DAEMON="python3 -m aawgd"
PIDFILE="/var/run/aawgd.pid"

start() {
    printf "Starting Android Auto Wireless Gateway: "
    start-stop-daemon --start --quiet --background \
        --make-pidfile --pidfile $PIDFILE \
        --exec /usr/bin/python3 -- -m aawgd
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping Android Auto Wireless Gateway: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
