name: Python Package Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'aa_wireless_dongle/package/aawg/**'
      - '.github/workflows/python-build.yml'

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        python3 -m pip install --user build

    - name: Build Python package
      run: |
        cd aa_wireless_dongle/package/aawg/src
        protoc --python_out=. --proto_path=proto proto/*.proto
        python3 -m build --wheel --outdir ./dist/

    - uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: aa_wireless_dongle/package/aawg/src/dist/*.whl
